apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
        - name: webpage
          image: pl0xi/webpage:0.1.9
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webpage
spec:
  type: LoadBalancer
  ports:
    - port: 3000  
      targetPort: 3000 
  selector:
    app: webpage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webpage-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: mtogo.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webpage
                port:
                  number: 3000
