apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  REACT_APP_BACKEND_URL: "http://167.71.45.53"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
        - name: webpage
          image: pl0xi/webpage:0.1.7
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REACT_APP_BACKEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: webpage
spec:
  type: LoadBalancer
  ports:
    - port: 3000  
      targetPort: 3000 
  selector:
    app: webpage
