apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
        - name: webpage
          image: pl0xi/webpage:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webpage
spec:
  type: LoadBalancer
  ports:
    - port: 3000  
      targetPort: 3000 
  selector:
    app: webpage