apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
        - name: webpage
          image: pl0xi/webpage:0.2.3
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "400m"
---
apiVersion: v1
kind: Service
metadata:
  name: webpage
spec:
  type: LoadBalancer
  ports:
    - port: 3000  
      targetPort: 3000 
  selector:
    app: webpage
