apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-database-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-database-order-service
  template:
    metadata:
      labels:
        app: postgres-database-order-service
    spec:
      containers:
        - name: postgres-container
          image: postgres:16
          ports:
            - containerPort: 5436 
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: md5
            - name: POSTGRES_USER  
              valueFrom:
                secretKeyRef:
                  name: db-order-credentials
                  key: db.order_service.username
            - name: POSTGRES_PASSWORD  
              valueFrom:
                secretKeyRef:
                  name: db-order-credentials
                  key: db.order_service.password
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-order-service
spec:
  selector:
    app: postgres-database-order-service
  ports:
    - protocol: TCP
      port: 5436
      targetPort: 5432
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-order-credentials
  namespace: default
spec:
  encryptedData:
    db.order_service.password: AgC9QeAD25+28cw3WFENwART+mSs55le+mJ+6iY/jBV9kKv6ZqjUgNk67n6w0mZ+y5ZlWJJ/FVzrzfJEOEIehaQlKFaU0fPiddum/zdO3s5PGiHZ4USYhqhRxc+6lHIyxgJ528+qHP3y86tvC8Ek6Ig1a9tDbt+Fo/X+s/wFN107U9GOZo8bB3gpO0TCmFE+WTdY1xCIDOXNCUi+HZke5IZM9txTobQrGu9qoGe5KKeNzQQLkHqRocEsoCXYG1U25giCkf7zDMV5B/k4OlQJCzdX5D1YWEK29iNdfjMbbYt8G0JKiBlfKTmPDoj0wStVBkcTR/GuOy2xsxen42wRulYdCOH2ecB47hFIWqxEDVRaNNkxqQ6XmYFUbIVRizlNpnwTkJujLvSbp6jzmRJhae/iNejOuwASJcUUIOtOs1bEsb/UOc94I06V2pF3TlJVvx5CXfo0DmgXq0QNV6oqzgKIhFp9x0kk+GmDcTK2IfNpCMIGWx4EC0eHLcytIicd5QpNztMo8NOoX2+O0rYqh0pePem4tvzVSqR5pGAcfgo7Au4HZ+bhbQyifN2Ssv79IWQdk7CMa9tadUqfn60Rainu0rcaq2HgXAWbL5rPiRQL8/WIIQ/zTfc1emoj0HyCx4fdQYwhLQpTC++dDxAmZeRNuUwdOEXSYKmUXY5N3zGCKRJO8+0mogXs2UZlIBvd6zPMC60Ici2zG6ZPI40=
    db.order_service.username: AgDhTEdcfWINY+oBwSK+00z2u4q49ntVYur/U/J5cN5QR5LefD5pPi7yKfj6cgihvTt4bnCs2Vxt0C1CLkebg6g6lUerGDfbp18L0CLlrZ7ENLK1iQvUz+iw1RE+u106P9GsbgquOe3ZyaMc5ZcsjeFO+WOO6AWopknCdMikmlMRKgH/JWUVyCnL/7x6k3+eTo95Qv03/zGhq0DIJ3weBD2V9K/P82JIfCRPTWCVpjNWKsHbnic2o2MrLiTHFrGijQ9cXVymAVVym1CG7f24SHniMNjLUFcT86DFPeBYr4+29IAIOZPBJ3D7WfbjiwwZ0djs8O8P7CtK/BnumPU3Ku6nKkylJIGIm+D3P+1gImaRVDnfl61e8JRJyLhKVJ3yZ9cvKx8KLUs9xmWCS78GqnK9SGEWSJ6UQDh3IxOblNimf8vXbLkNT9E0P6fN4WQkG9ST+aLsNOKZncc5TjIqy130N76uWZxz1GNxG0dlrzpbVt9zd2WFdCg/Io9cqQjX5834i0oh0VqbJjtxGhioW3GEhm8sCt2aFnalUZ2X/oskqqy1PkTDcNOzn7rJB/0Ncp5w2v2rDxESJ1Oe65gpTzAZu10P9IQvMckuL0y0ixHaU3d521kCgn5qqHCl6LM/M17c7GRoZY/jtvbIr7K/Uw+MdWaZlZltFlB4ewcIj++q1VxWMAS3+/taa4XHiboON/oWF+fV6Xpr4bqo
  template:
    metadata:
      creationTimestamp: null
      name: db-order-credentials
      namespace: default