apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      nodeSelector:
        custom-label: agentnode
      containers:
        - name: order-service
          image: pl0xi/order_service:0.0.4
          env:
          - name: DB_ORDER_SERVER_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-orders-credentials
                key: db.order_service.username
          - name: DB_ORDER_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-orders-credentials
                key: db.order_service.password
          - name: P_KEY_AUTH
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: pkey.jwt
          ports:
            - containerPort: 8084
          resources:
            requests:
              memory: "200Mi"
            limits:
              memory: "700Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  ports:
    - port: 8084  
      targetPort: 8084 
  selector:
    app: order-service
