apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      nodeSelector:
        custom-label: agentnode
      containers:
        - name: auth-service
          image: pl0xi/auth_service:0.0.8
          env:
          - name: DB_AUTH_SERVER_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-auth-credentials
                key: db.auth_service.username
          - name: DB_AUTH_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-auth-credentials
                key: db.auth_service.password
          ports:
            - containerPort: 8086
          resources:
            requests:
              memory: "200Mi"
            limits:
              memory: "700Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer
  ports:
    - port: 8086  
      targetPort: 8086 
  selector:
    app: auth-service
