apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-database-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-database-auth-service
  template:
    metadata:
      labels:
        app: postgres-database-auth-service
    spec:
      containers:
        - name: postgres-container
          image: postgres:16
          ports:
            - containerPort: 5432 
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: md5
            - name: POSTGRES_USER  
              value: postgres # TODO: Use github secrets
            - name: POSTGRES_PASSWORD  
              value: password # TODO: Use github secrets
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-database-auth-service
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432