apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-database-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-database-auth-service
  template:
    metadata:
      labels:
        app: postgres-database-auth-service
    spec:
      containers:
        - name: postgres-container
          image: postgres:16
          ports:
            - containerPort: 5432 
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "200Mi"
              cpu: "100m"
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: md5
            - name: POSTGRES_USER  
              valueFrom:
                secretKeyRef:
                  name: db-auth-credentials
                  key: db.auth_service.username
            - name: POSTGRES_PASSWORD  
              valueFrom:
                secretKeyRef:
                  name: db-auth-credentials
                  key: db.auth_service.password
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-database-auth-service
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-auth-credentials
  namespace: default
spec:
  encryptedData:
    db.auth_service.password: AgBoCG9uYrWWzrVwi9PvN64lXOasluM0/0CowLliA182BCgNk0J1AAUhMZwgC7oRiza3VPeaOOumtBr6CV/TwO0bSmp03vlUz4fPo6ipLWZk1xbFGzrCr1VLjJdUnAUqnp4sVPxLBumL9jJTLY+z2qDTTUqIIfCo+wSgDCmnNkO9tJ9zb+vX+Q1MoWe2PsO79UAxnusEECzh0dkuWUjVtwcWpX7pNzYMFkQHxqY2zdqTY1+cTocBE1oqbAa/2usBkfnSKIiNy2GS2dRA3WfcqiE2f08vsGMjLDyLLhIgWOV4w4l9FWxbucCj2jk/nEN4O7PVBqyv4ZopOrD2r+J2oNgzBjnqvmwEYApjXxiMm27Qib0FrtXT9l5JzkS4kkMLBTL7aeWrXlLAQjvv83S+zflpjZw7fk1P3lFxbVSm8OSvbYGdmuon9f3zBnT6OkjqbYn0auYhRMRhraA6dG+QhpuOd5dbJ8UptynkOSubcdciud5sJsA3WOY42jY75kDG7qXQFW1Wxf4OEVw233ObTX9hoGvA/xBF3anZ189VPLhHz/uemiMQUrZVjVhGT4+tKufC67kjZ9viDP5kfOgti82jFWgE7SVoLX1k7XpCJ20pgEyp3he3hpnwGENk9GNuAPpcuCXBvXYjFWpkeGIFOZk/egnHFWcsW96++krvtvmrt8u9zsp3OrRiV/UJ3ODt5wEyomTSqT8IINZao6w=
    db.auth_service.username: AgB/pMZ2ggEw6xbtWeAKEgUwJ42TW6EICiW1EBDJoCCmhVOUtR4U8k9JJGeiZY/dhaWg3TPGgajADGDxzTFsdun4i3Chy98DNkUUQN5ejNTiEdpyXaRf0PyDXeA8/IaQWOVl2qiZ6fx9ruqoENo9eMy7OprX4a8lAImGfo1K7Z4bl8oI8PlJeVR1/KZEkLqgERv0OKpBJqLumOjNehuG5NUf1Lw7wl60mZriouOxgziWjvg0nGHV2WpaCD3Zr5g5/n+VS7RrZlSOA7OnyCiYc1J4sFgWdkxB1GEn0Zxybq/YZbAGcm2C5oG29X0D3xowCKgoHTu1gaX7hkkLBEm33jnqNSmtyPtihdcY8VtNFSm/qH4cDrkzVXYnKPNWOSFyHe9CTIi2Ro4PiMnEtSSj3oqUM/5Emn5nHrkQTxH+IRoLxZS9TjyaHGWsupRrzORM7DXm0uWwZBwK0+NfHFRCpRbtyhId7gWpzcAMKSbNg1nVeaAw0T/HVhP34FJFaihw8YJ7QwufEPJ4ErI7JzmF3hiW5QQpz1qRMEZRpFTW3LY6rOuO6Vxk5MCPy1IA3ADJ8UfWGljARqLzV0ctT8MNazQnBYbsr3pDsjHCpjiGqmX7FKL3/M08xiJpOB24IXoTLnAsHSDcCpEQq/AhRf/RVpZ9XHUWUqB87tcnFbdiI9g/b2UKidEBnPl9f3MgzNlCZV+Gx3/TXV/N+yc=
  template:
    metadata:
      creationTimestamp: null
      name: db-auth-credentials
      namespace: default
