apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-service
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: camunda-service
  template:
    metadata:
      labels:
        app: camunda-service
    spec:
      containers:
        - name: camunda-service
          image: pl0xi/camunda_service:0.0.1
          ports:
            - containerPort: 8087
          resources:
            requests:
              memory: "260Mi"
              cpu: "10m"
            limits:
              memory: "400Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: camunda-service
spec:
  type: LoadBalancer
  ports:
    - port: 8087  
      targetPort: 8087 
  selector:
    app: camunda-service
