apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-service
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: camel-service
  template:
    metadata:
      labels:
        app: camel-service
    spec:
      nodeSelector:
        custom-label: agentnode
      containers:
        - name: camel-service
          image: pl0xi/camel_service:0.1.0
          ports:
            - containerPort: 9090
            - containerPort: 8081
          resources:
            requests:
              memory: "260Mi"
            limits:
              memory: "400Mi"
          env:
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq.username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq.password
---
apiVersion: v1
kind: Service
metadata:
  name: camel-service-grpc
  namespace: default
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 9090
  selector:
    app: camel-service
  type: LoadBalancer
